/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => NotebookDigitizerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  apiKey: "",
  model: "gemini-3.8-flash",
  customModel: "",
  attachmentFolder: "scans",
  embedCallouts: true,
  enablePageBreaks: false,
  calloutTitle: "Original Scan",
  customPrompt: ""
};
var AVAILABLE_MODELS = [
  { id: "gemini-3.8-flash", name: "Gemini 3.8 Flash (Latest - Fast & Recommended)" },
  { id: "gemini-3.1-pro", name: "Gemini 3.1 Pro (Most Capable for Complex Handwriting)" },
  { id: "gemini-3.5-flash-lite", name: "Gemini 3.5 Flash-Lite (High Throughput)" },
  { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash" },
  { id: "gemini-2.0-flash", name: "Gemini 2.0 Flash" },
  { id: "gemini-1.5-flash", name: "Gemini 1.5 Flash" },
  { id: "gemini-1.5-pro", name: "Gemini 1.5 Pro" },
  { id: "custom", name: "Custom Model (specify below)..." }
];
function getEffectiveModel(settings) {
  if (settings.model === "custom" && settings.customModel.trim()) {
    return settings.customModel.trim();
  }
  return settings.model || "gemini-3.8-flash";
}
var NotebookDigitizerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Handwritten Notebook Digitizer Settings" });
    const keySetting = new import_obsidian.Setting(containerEl).setName("Gemini API Key").setDesc("Each user should provide their own free Google Gemini API key. Keys are saved locally in your vault.").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("AIzaSy...").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value.trim();
        await this.plugin.saveSettings();
      });
    });
    keySetting.descEl.createEl("br");
    const link = keySetting.descEl.createEl("a", {
      text: "Get your free API key at Google AI Studio (aistudio.google.com/app/apikey)",
      href: "https://aistudio.google.com/app/apikey"
    });
    link.setAttr("target", "_blank");
    new import_obsidian.Setting(containerEl).setName("Gemini Model").setDesc("Select the model to use for handwriting recognition. Defaults to Gemini 3.8 Flash.").addDropdown((dropdown) => {
      for (const model of AVAILABLE_MODELS) {
        dropdown.addOption(model.id, model.name);
      }
      dropdown.setValue(this.plugin.settings.model);
      dropdown.onChange(async (value) => {
        this.plugin.settings.model = value;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    if (this.plugin.settings.model === "custom") {
      new import_obsidian.Setting(containerEl).setName("Custom Model Name").setDesc("Enter any valid Gemini model identifier from Google AI Studio (e.g. gemini-3.8-flash).").addText((text) => {
        text.setPlaceholder("e.g. gemini-3.8-flash").setValue(this.plugin.settings.customModel).onChange(async (value) => {
          this.plugin.settings.customModel = value.trim();
          await this.plugin.saveSettings();
        });
      });
    }
    new import_obsidian.Setting(containerEl).setName("Embed Scans in Collapsible Callouts").setDesc("Embed original page scans inside a collapsible callout for easy proofreading.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.embedCallouts).onChange(async (value) => {
        this.plugin.settings.embedCallouts = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Callout Title").setDesc("Default title for the collapsible image callout (e.g., 'Original Scan' or '\u0635\u0648\u0631\u0629 \u0627\u0644\u0635\u0641\u062D\u0629 \u0627\u0644\u0623\u0635\u0644\u064A\u0629').").addText((text) => {
      text.setPlaceholder("Original Scan").setValue(this.plugin.settings.calloutTitle).onChange(async (value) => {
        this.plugin.settings.calloutTitle = value.trim() || "Original Scan";
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Scans Subfolder").setDesc("Name of the subfolder under the note's directory where uploaded page scans will be stored (defaults to 'scans'). Keeps your notes directory clean.").addText((text) => {
      text.setPlaceholder("scans").setValue(this.plugin.settings.attachmentFolder).onChange(async (value) => {
        this.plugin.settings.attachmentFolder = value.trim() || "scans";
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Default Custom Instructions").setDesc("Optional persistent instructions added to every transcription prompt (e.g., preferred formatting, vocabulary).").addTextArea((textArea) => {
      textArea.setPlaceholder("e.g. Prefer Modern Standard Arabic formatting. Keep English programming terms in inline code blocks.").setValue(this.plugin.settings.customPrompt).onChange(async (value) => {
        this.plugin.settings.customPrompt = value;
        await this.plugin.saveSettings();
      });
      textArea.inputEl.rows = 4;
      textArea.inputEl.cols = 40;
    });
  }
};

// src/modal.ts
var import_obsidian4 = require("obsidian");

// src/gemini.ts
var import_obsidian2 = require("obsidian");

// src/prompts.ts
function buildSystemPrompt(userCustomPrompt, noteSpecificInstruction, enablePageBreaks = false) {
  const multiPageInstruction = enablePageBreaks ? `3. Multiple Pages:
   - When provided with multiple images (representing consecutive pages of a notebook), transcribe each page in order.
   - At the beginning of the transcription for each page, insert a clear marker:
     <!-- PAGE_BREAK: 1 -->
     (for page 1),
     <!-- PAGE_BREAK: 2 -->
     (for page 2), etc.
   - If a sentence or list item begins at the bottom of one page and continues onto the next, transcribe the continuation naturally across the page marker without repeating words.` : `3. Multiple Pages:
   - When provided with multiple images (representing consecutive pages of a notebook), transcribe them into ONE seamless, continuous document.
   - Do NOT insert artificial page break lines, dividers, or page markers between pages.
   - If a sentence, paragraph, or list item starts on one page and continues onto the next, flow it naturally and seamlessly without interruption.`;
  let prompt = `You are an expert transcriber of handwritten notebooks and documents.
Your task is to accurately transcribe handwritten pages into clean, well-structured Markdown notes.

### Core Guidelines:
1. Language & Script:
   - Handle Arabic, English, or mixed bilingual handwriting seamlessly.
   - Maintain natural sentence flow and correct grammar.
   - For messy, hurried, or unclear handwriting, use the surrounding sentence context, domain vocabulary, and grammatical rules to transcribe the most plausible and accurate words. Do not skip or summarize text.

2. Structure & Formatting:
   - Replicate the document's structure faithfully using standard Markdown:
     - Main titles / subject headers: use '# ' or '## ' matching visual prominence.
     - Subheadings and section headers: use '### ' or '#### '.
     - Bullet points: use '- '.
     - Numbered lists: use '1. ', '2. ', etc.
     - Checklists: use '- [ ] ' or '- [x] '.
     - Tables: convert handwritten tables into clean Markdown tables '| Header | Header |'.
     - Math & Equations: convert formulas into LaTeX syntax ('$inline$' or '$$block$$').
     - Code / technical terms: use inline code \`code\` or code blocks.
     - Quotes or highlighted callouts: use blockquotes '> '.

${multiPageInstruction}

4. Fidelity:
   - Do NOT add conversational filler, preambles, or postscripts (e.g., do NOT say "Here is the transcription:").
   - Output ONLY the transcribed Markdown content.
`;
  if (userCustomPrompt && userCustomPrompt.trim()) {
    prompt += `
### Persistent User Instructions:
${userCustomPrompt.trim()}
`;
  }
  if (noteSpecificInstruction && noteSpecificInstruction.trim()) {
    prompt += `
### Specific Instructions for this Batch:
${noteSpecificInstruction.trim()}
`;
  }
  return prompt;
}

// src/gemini.ts
async function transcribeImagesWithGemini(request) {
  const { apiKey, model, images, userCustomPrompt, noteSpecificInstruction, enablePageBreaks } = request;
  if (!apiKey || apiKey.trim().length === 0) {
    throw new Error("Gemini API key is not configured. Please add your API key in Settings > Handwritten Notebook Digitizer.");
  }
  if (!images || images.length === 0) {
    throw new Error("No images provided for transcription.");
  }
  const promptText = buildSystemPrompt(userCustomPrompt, noteSpecificInstruction, !!enablePageBreaks);
  const parts = [
    {
      text: promptText
    }
  ];
  for (let i = 0; i < images.length; i++) {
    const img = images[i];
    parts.push({
      inline_data: {
        mime_type: img.mimeType || "image/jpeg",
        data: img.base64Data
      }
    });
  }
  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(apiKey.trim())}`;
  const requestPayload = {
    contents: [
      {
        parts
      }
    ],
    generationConfig: {
      temperature: 0.1,
      maxOutputTokens: 8192
    }
  };
  let lastError = null;
  const maxRetries = 2;
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      if (attempt > 0) {
        await new Promise((resolve) => setTimeout(resolve, attempt * 1500));
      }
      const response = await (0, import_obsidian2.requestUrl)({
        url: endpoint,
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify(requestPayload)
      });
      if (response.status !== 200) {
        if ((response.status === 503 || response.status === 500) && attempt < maxRetries) {
          lastError = { status: response.status, text: response.text };
          continue;
        }
        handleHttpError(response.status, response.text, model);
      }
      const data = response.json;
      const candidate = data?.candidates?.[0];
      if (!candidate) {
        throw new Error("Gemini returned no response candidates. Please verify image clarity or try another model.");
      }
      if (candidate.finishReason === "SAFETY") {
        throw new Error("Gemini blocked the response due to content safety settings.");
      }
      const textParts = candidate.content?.parts;
      if (!textParts || textParts.length === 0) {
        throw new Error("Gemini returned an empty transcription response.");
      }
      let fullTranscription = "";
      for (const part of textParts) {
        if (part.text) {
          fullTranscription += part.text;
        }
      }
      return fullTranscription.trim();
    } catch (error) {
      lastError = error;
      if ((error.status === 503 || error.status === 500) && attempt < maxRetries) {
        continue;
      }
      if (error.status) {
        handleHttpError(error.status, error.text || error.message, model);
      }
      throw error;
    }
  }
  if (lastError) {
    if (lastError.status) {
      handleHttpError(lastError.status, lastError.text || lastError.message, model);
    }
    throw lastError;
  }
  throw new Error("Failed to communicate with Gemini API.");
}
function handleHttpError(status, messageText, modelName) {
  if (status === 400) {
    throw new Error(`Gemini API Error (400 Bad Request): The request payload was rejected. ${messageText || ""}`);
  } else if (status === 403) {
    throw new Error("Gemini API Error (403 Forbidden): Invalid API key or permission denied. Please verify your API key.");
  } else if (status === 404) {
    throw new Error(`Gemini API Error (404 Not Found): The model '${modelName || ""}' was not found. Please check your model setting.`);
  } else if (status === 429) {
    throw new Error("Gemini API Error (429 Rate Limit Exceeded): Quota exceeded. Please wait a few moments before trying again.");
  } else if (status === 503) {
    throw new Error(`Gemini API Server Error (503 Service Unavailable): The model '${modelName || ""}' is temporarily overloaded on Google's servers. Please try again in a few moments, or select another model in settings (e.g. Gemini 2.0 Flash or Gemini 1.5 Flash).`);
  } else if (status >= 500) {
    throw new Error(`Gemini API Server Error (${status}): Google's servers encountered an error. Please try again in a few moments.`);
  } else {
    throw new Error(`Gemini API Error (${status}): ${messageText || "Unknown error occurred"}`);
  }
}

// src/noteBuilder.ts
var import_obsidian3 = require("obsidian");
async function ensureFolderExists(app, folderPath) {
  const normalized = (0, import_obsidian3.normalizePath)(folderPath);
  if (!normalized || normalized === "/" || normalized === ".") return;
  const parts = normalized.split("/").filter((p) => p.length > 0);
  let current = "";
  for (const part of parts) {
    current = current ? `${current}/${part}` : part;
    const existing = app.vault.getAbstractFileByPath(current);
    if (!existing) {
      await app.vault.createFolder(current);
    }
  }
}
async function saveImagesToVault(app, images, settings, noteFolderPath) {
  const savedFiles = [];
  const subfolderSetting = (settings.attachmentFolder || "").trim() || "scans";
  let targetFolder;
  const cleanParent = !noteFolderPath || noteFolderPath === "/" ? "" : (0, import_obsidian3.normalizePath)(noteFolderPath);
  if (subfolderSetting.startsWith("/")) {
    targetFolder = (0, import_obsidian3.normalizePath)(subfolderSetting.substring(1));
  } else if (subfolderSetting.includes("/")) {
    targetFolder = (0, import_obsidian3.normalizePath)(subfolderSetting);
  } else {
    targetFolder = cleanParent ? (0, import_obsidian3.normalizePath)(`${cleanParent}/${subfolderSetting}`) : subfolderSetting;
  }
  await ensureFolderExists(app, targetFolder);
  for (let i = 0; i < images.length; i++) {
    const img = images[i];
    let targetPath = (0, import_obsidian3.normalizePath)(`${targetFolder}/${img.name}`);
    targetPath = getUniqueFilePath(app, targetPath);
    const createdFile = await app.vault.createBinary(targetPath, img.arrayBuffer);
    savedFiles.push(createdFile);
  }
  return savedFiles;
}
function formatNoteWithCallouts(app, transcription, savedFiles, settings, sourcePath) {
  const calloutTitle = settings.calloutTitle || "Original Scan";
  if (settings.enablePageBreaks && savedFiles.length > 1) {
    const pageBreakRegex = /<!--\s*(?:PAGE_BREAK|PAGE)\s*:\s*(?:Page\s*)?(\d+)\s*-->/gi;
    const matches = [...transcription.matchAll(pageBreakRegex)];
    if (matches.length > 0) {
      const sections = [];
      const preamble = transcription.substring(0, matches[0].index).trim();
      if (preamble.length > 0) {
        sections.push(preamble);
      }
      for (let i = 0; i < matches.length; i++) {
        const match = matches[i];
        const pageNum = parseInt(match[1], 10);
        const startIndex = match.index + match[0].length;
        const endIndex = i + 1 < matches.length ? matches[i + 1].index : transcription.length;
        const pageText = transcription.substring(startIndex, endIndex).trim();
        const fileIndex = pageNum - 1;
        const file = fileIndex < savedFiles.length ? savedFiles[fileIndex] : null;
        let pageBlock = "";
        if (settings.embedCallouts && file) {
          const link = app.fileManager.generateMarkdownLink(file, sourcePath);
          const title = `${calloutTitle} (Page ${pageNum})`;
          pageBlock += `> [!info]- ${title}
> ${link}

`;
        }
        pageBlock += pageText;
        sections.push(pageBlock);
      }
      return sections.join("\n\n---\n\n");
    }
  }
  const cleanedTranscription = transcription.replace(/<!--\s*(?:PAGE_BREAK|PAGE)\s*:\s*(?:Page\s*)?\d+\s*-->/gi, "").trim();
  if (!settings.embedCallouts || savedFiles.length === 0) {
    return cleanedTranscription;
  }
  let headerCallouts = "";
  for (let i = 0; i < savedFiles.length; i++) {
    const file = savedFiles[i];
    const link = app.fileManager.generateMarkdownLink(file, sourcePath);
    const title = savedFiles.length > 1 ? `${calloutTitle} (Page ${i + 1})` : calloutTitle;
    headerCallouts += `> [!info]- ${title}
> ${link}

`;
  }
  return `${headerCallouts}${cleanedTranscription}`;
}
async function writeNoteContent(app, formattedContent, targetMode, activeFile, newNoteTitle, noteFolderPath) {
  if (targetMode === "append" && activeFile) {
    const existingContent = await app.vault.read(activeFile);
    const divider = existingContent.trim().length > 0 ? "\n\n---\n\n" : "";
    const updatedContent = `${existingContent.trim()}${divider}${formattedContent}`;
    await app.vault.modify(activeFile, updatedContent);
    return {
      targetFile: activeFile,
      isNewFile: false
    };
  }
  const baseName = newNoteTitle && newNoteTitle.trim().length > 0 ? newNoteTitle.trim() : `Handwritten Note ${getFormattedDate()}`;
  const cleanParent = !noteFolderPath || noteFolderPath === "/" ? "" : (0, import_obsidian3.normalizePath)(noteFolderPath);
  let filePath = (0, import_obsidian3.normalizePath)(cleanParent ? `${cleanParent}/${baseName}.md` : `${baseName}.md`);
  filePath = getUniqueFilePath(app, filePath);
  const createdFile = await app.vault.create(filePath, formattedContent);
  return {
    targetFile: createdFile,
    isNewFile: true
  };
}
function getUniqueFilePath(app, targetPath) {
  let path = (0, import_obsidian3.normalizePath)(targetPath);
  if (!app.vault.getAbstractFileByPath(path)) {
    return path;
  }
  const lastDot = path.lastIndexOf(".");
  const basePath = lastDot !== -1 ? path.substring(0, lastDot) : path;
  const ext = lastDot !== -1 ? path.substring(lastDot) : "";
  let counter = 1;
  while (app.vault.getAbstractFileByPath(`${basePath} (${counter})${ext}`)) {
    counter++;
  }
  return `${basePath} (${counter})${ext}`;
}
function getFormattedDate() {
  const now = /* @__PURE__ */ new Date();
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, "0");
  const d = String(now.getDate()).padStart(2, "0");
  const h = String(now.getHours()).padStart(2, "0");
  const min = String(now.getMinutes()).padStart(2, "0");
  return `${y}-${m}-${d} ${h}-${min}`;
}

// src/modal.ts
var DigitizeModal = class extends import_obsidian4.Modal {
  constructor(app, plugin, initialTargetMode) {
    super(app);
    this.selectedImages = [];
    this.customInstructions = "";
    this.targetMode = "new";
    this.newNoteTitle = "";
    this.activeFile = null;
    this.isProcessing = false;
    this.showKeyInput = false;
    this.enablePageBreaks = false;
    this.statusMessageEl = null;
    this.submitButtonEl = null;
    this.plugin = plugin;
    this.activeFile = this.app.workspace.getActiveFile();
    this.enablePageBreaks = this.plugin.settings.enablePageBreaks ?? false;
    if (initialTargetMode) {
      this.targetMode = initialTargetMode;
    } else if (this.activeFile && this.activeFile.extension === "md") {
      this.targetMode = "new";
    }
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    this.modalEl.addClass("notebook-digitizer-modal-window");
    contentEl.addClass("notebook-digitizer-modal");
    contentEl.createEl("h2", { text: "Digitize Handwritten Pages", cls: "digitizer-modal-title" });
    this.renderApiKeySection(contentEl);
    this.renderUploadControls(contentEl);
    const galleryContainer = contentEl.createDiv({ cls: "digitizer-gallery-container" });
    this.renderGallery(galleryContainer);
    const instructionsSection = contentEl.createDiv({ cls: "digitizer-field-section" });
    instructionsSection.createEl("label", {
      cls: "digitizer-field-label",
      text: "Specific Instructions (Optional)"
    });
    instructionsSection.createEl("p", {
      cls: "digitizer-field-desc",
      text: "Ask AI to ignore parts, emphasize key points, etc."
    });
    const instructionsInput = instructionsSection.createEl("textarea", {
      cls: "digitizer-instructions-input"
    });
    instructionsInput.rows = 2;
    instructionsInput.placeholder = "e.g. Ignore pencil doodles at the bottom, keep formulas in LaTeX...";
    instructionsInput.value = this.customInstructions;
    instructionsInput.addEventListener("input", (e) => {
      this.customInstructions = e.target.value;
    });
    const destinationSection = contentEl.createDiv({ cls: "digitizer-destination-section" });
    destinationSection.createEl("h4", { text: "Destination Note" });
    const modeContainer = destinationSection.createDiv({ cls: "digitizer-mode-options" });
    const newNoteLabel = modeContainer.createEl("label", { cls: "digitizer-radio-label" });
    const newNoteRadio = newNoteLabel.createEl("input", { type: "radio", value: "new" });
    newNoteRadio.name = "digitizer-target-mode";
    newNoteRadio.checked = this.targetMode === "new";
    newNoteLabel.appendText(" Create New Note");
    const titleInputContainer = destinationSection.createDiv({ cls: "digitizer-title-container" });
    titleInputContainer.createEl("label", {
      cls: "digitizer-field-label",
      text: "Note Title"
    });
    const titleInput = titleInputContainer.createEl("input", {
      type: "text",
      cls: "digitizer-title-input"
    });
    titleInput.placeholder = `e.g. Lecture Notes - ${(/* @__PURE__ */ new Date()).toISOString().slice(0, 10)}`;
    titleInput.value = this.newNoteTitle;
    titleInput.addEventListener("input", (e) => {
      this.newNoteTitle = e.target.value;
    });
    const appendLabel = modeContainer.createEl("label", { cls: "digitizer-radio-label" });
    const appendRadio = appendLabel.createEl("input", { type: "radio", value: "append" });
    appendRadio.name = "digitizer-target-mode";
    appendRadio.checked = this.targetMode === "append";
    if (this.activeFile && this.activeFile.extension === "md") {
      appendLabel.appendText(` Append to Active Note: "${this.activeFile.basename}"`);
    } else {
      appendLabel.appendText(" Append to Active Note (No markdown note currently open)");
      appendRadio.disabled = true;
    }
    newNoteRadio.addEventListener("change", () => {
      this.targetMode = "new";
      titleInputContainer.style.display = "block";
    });
    appendRadio.addEventListener("change", () => {
      this.targetMode = "append";
      titleInputContainer.style.display = "none";
    });
    if (this.targetMode === "append") {
      titleInputContainer.style.display = "none";
    }
    const optionsSection = contentEl.createDiv({ cls: "digitizer-options-section" });
    const pageBreakLabel = optionsSection.createEl("label", { cls: "digitizer-checkbox-label" });
    const pageBreakCheckbox = pageBreakLabel.createEl("input", { type: "checkbox" });
    pageBreakCheckbox.checked = this.enablePageBreaks;
    pageBreakLabel.appendText(" Separate pages with page breaks");
    const pageBreakDesc = optionsSection.createEl("p", {
      cls: "digitizer-checkbox-desc",
      text: "Disabled by default: combines multiple pages into one continuous note without dividers."
    });
    pageBreakCheckbox.addEventListener("change", async () => {
      this.enablePageBreaks = pageBreakCheckbox.checked;
      this.plugin.settings.enablePageBreaks = this.enablePageBreaks;
      await this.plugin.saveSettings();
    });
    this.statusMessageEl = contentEl.createDiv({ cls: "digitizer-status-message" });
    const buttonContainer = contentEl.createDiv({ cls: "digitizer-button-bar" });
    const cancelBtn = buttonContainer.createEl("button", { text: "Cancel" });
    cancelBtn.addEventListener("click", () => this.close());
    this.submitButtonEl = buttonContainer.createEl("button", {
      text: "Digitize & Transcribe",
      cls: "mod-cta digitizer-submit-btn"
    });
    this.submitButtonEl.addEventListener("click", () => this.handleProcess());
  }
  renderApiKeySection(parentEl) {
    if (!this.plugin.settings.apiKey || this.showKeyInput) {
      const keyCard = parentEl.createDiv({ cls: "digitizer-key-card" });
      const header = keyCard.createDiv({ cls: "digitizer-key-header" });
      header.createEl("strong", { text: "\u{1F511} Your Personal Gemini API Key" });
      const desc = keyCard.createEl("p", { cls: "digitizer-key-desc" });
      desc.createSpan({ text: "Provide your own free Google Gemini API key. Keys are saved locally in your vault. " });
      const link = desc.createEl("a", {
        text: "Get free key from Google AI Studio",
        href: "https://aistudio.google.com/app/apikey"
      });
      link.setAttr("target", "_blank");
      const inputRow = keyCard.createDiv({ cls: "digitizer-key-input-row" });
      const keyInput = inputRow.createEl("input", {
        type: "password",
        placeholder: "Paste your API key here (AIzaSy...)",
        cls: "digitizer-key-input"
      });
      keyInput.value = this.plugin.settings.apiKey;
      const saveKeyBtn = inputRow.createEl("button", {
        text: "Save Key",
        cls: "mod-cta digitizer-save-key-btn"
      });
      saveKeyBtn.addEventListener("click", async () => {
        const val = keyInput.value.trim();
        if (val) {
          this.plugin.settings.apiKey = val;
          await this.plugin.saveSettings();
          this.showKeyInput = false;
          new import_obsidian4.Notice("Personal Gemini API key saved!");
          this.onOpen();
        } else {
          new import_obsidian4.Notice("Please enter a valid API key.");
        }
      });
      if (this.plugin.settings.apiKey && this.showKeyInput) {
        const cancelBtn = inputRow.createEl("button", { text: "Cancel" });
        cancelBtn.addEventListener("click", () => {
          this.showKeyInput = false;
          this.onOpen();
        });
      }
    } else {
      const statusRow = parentEl.createDiv({ cls: "digitizer-key-status-row" });
      const keyInfo = statusRow.createDiv({ cls: "digitizer-key-info-left" });
      keyInfo.createSpan({
        text: `\u{1F511} Key: \u2022\u2022\u2022\u2022${this.plugin.settings.apiKey.slice(-4)} `,
        cls: "digitizer-key-status-text"
      });
      const changeLink = keyInfo.createEl("a", { text: "(edit)", cls: "digitizer-change-key-link" });
      changeLink.addEventListener("click", (e) => {
        e.preventDefault();
        this.showKeyInput = true;
        this.onOpen();
      });
      const modelWrap = statusRow.createDiv({ cls: "digitizer-model-select-wrap" });
      modelWrap.createSpan({ text: "Model: ", cls: "digitizer-model-label" });
      const modelSelect = modelWrap.createEl("select", { cls: "digitizer-model-select" });
      for (const m of AVAILABLE_MODELS) {
        const opt = modelSelect.createEl("option", { value: m.id, text: m.name });
        if (m.id === this.plugin.settings.model) opt.selected = true;
      }
      modelSelect.addEventListener("change", async () => {
        this.plugin.settings.model = modelSelect.value;
        await this.plugin.saveSettings();
        new import_obsidian4.Notice(`Switched model to ${modelSelect.value}`);
      });
    }
  }
  renderUploadControls(parentEl) {
    const uploadBar = parentEl.createDiv({ cls: "digitizer-upload-bar" });
    const fileInput = uploadBar.createEl("input", {
      type: "file",
      cls: "digitizer-hidden-input"
    });
    fileInput.multiple = true;
    fileInput.accept = "image/*";
    const cameraInput = uploadBar.createEl("input", {
      type: "file",
      cls: "digitizer-hidden-input"
    });
    cameraInput.accept = "image/*";
    cameraInput.setAttribute("capture", "environment");
    const selectFilesBtn = uploadBar.createEl("button", {
      text: "\u{1F4C1} Choose Images",
      cls: "digitizer-btn"
    });
    selectFilesBtn.addEventListener("click", () => fileInput.click());
    const cameraBtn = uploadBar.createEl("button", {
      text: "\u{1F4F7} Capture with Camera",
      cls: "digitizer-btn"
    });
    cameraBtn.addEventListener("click", () => cameraInput.click());
    const fileHandler = (e) => {
      const target = e.target;
      if (target.files && target.files.length > 0) {
        this.addFiles(Array.from(target.files));
        target.value = "";
      }
    };
    fileInput.addEventListener("change", fileHandler);
    cameraInput.addEventListener("change", fileHandler);
    const dropZone = parentEl.createDiv({ cls: "digitizer-drop-zone" });
    dropZone.createEl("span", { text: "Or drag & drop notebook page images here" });
    dropZone.addEventListener("dragover", (e) => {
      e.preventDefault();
      dropZone.addClass("drag-over");
    });
    dropZone.addEventListener("dragleave", () => {
      dropZone.removeClass("drag-over");
    });
    dropZone.addEventListener("drop", (e) => {
      e.preventDefault();
      dropZone.removeClass("drag-over");
      if (e.dataTransfer?.files && e.dataTransfer.files.length > 0) {
        const imageFiles = Array.from(e.dataTransfer.files).filter((f) => f.type.startsWith("image/"));
        if (imageFiles.length > 0) {
          this.addFiles(imageFiles);
        } else {
          new import_obsidian4.Notice("Please drop valid image files (JPG, PNG, WebP).");
        }
      }
    });
  }
  addFiles(files) {
    for (const file of files) {
      const item = {
        id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
        file,
        previewUrl: URL.createObjectURL(file),
        name: file.name
      };
      this.selectedImages.push(item);
    }
    const gallery = this.contentEl.querySelector(".digitizer-gallery-container");
    if (gallery) {
      this.renderGallery(gallery);
    }
  }
  renderGallery(container) {
    container.empty();
    if (this.selectedImages.length === 0) {
      container.createDiv({
        text: "No images selected yet. Choose 1\u20133 pages from notebook.",
        cls: "digitizer-gallery-empty"
      });
      return;
    }
    const list = container.createDiv({ cls: "digitizer-gallery-list" });
    this.selectedImages.forEach((img, index) => {
      const card = list.createDiv({ cls: "digitizer-image-card" });
      const badge = card.createDiv({ cls: "digitizer-page-badge", text: `Page ${index + 1}` });
      const imgEl = card.createEl("img", { cls: "digitizer-thumb" });
      imgEl.src = img.previewUrl;
      const info = card.createDiv({ cls: "digitizer-card-info" });
      info.createEl("span", { cls: "digitizer-card-name", text: img.name });
      const cardActions = card.createDiv({ cls: "digitizer-card-actions" });
      if (index > 0) {
        const moveLeftBtn = cardActions.createEl("button", { text: "\u25C0", cls: "digitizer-icon-btn" });
        moveLeftBtn.title = "Move page earlier";
        moveLeftBtn.addEventListener("click", () => {
          const temp = this.selectedImages[index - 1];
          this.selectedImages[index - 1] = this.selectedImages[index];
          this.selectedImages[index] = temp;
          this.renderGallery(container);
        });
      }
      if (index < this.selectedImages.length - 1) {
        const moveRightBtn = cardActions.createEl("button", { text: "\u25B6", cls: "digitizer-icon-btn" });
        moveRightBtn.title = "Move page later";
        moveRightBtn.addEventListener("click", () => {
          const temp = this.selectedImages[index + 1];
          this.selectedImages[index + 1] = this.selectedImages[index];
          this.selectedImages[index] = temp;
          this.renderGallery(container);
        });
      }
      const removeBtn = cardActions.createEl("button", { text: "\u2715", cls: "digitizer-icon-btn digitizer-remove-btn" });
      removeBtn.title = "Remove page";
      removeBtn.addEventListener("click", () => {
        URL.revokeObjectURL(img.previewUrl);
        this.selectedImages.splice(index, 1);
        this.renderGallery(container);
      });
    });
  }
  async handleProcess() {
    if (this.isProcessing) return;
    if (this.selectedImages.length === 0) {
      new import_obsidian4.Notice("Please select or capture at least one notebook page image.");
      return;
    }
    if (!this.plugin.settings.apiKey) {
      new import_obsidian4.Notice("Please set your Gemini API key first.");
      return;
    }
    this.setLoading(true, "Optimizing and encoding images...");
    try {
      const preparedImages = [];
      for (let i = 0; i < this.selectedImages.length; i++) {
        const item = this.selectedImages[i];
        this.updateStatus(`Optimizing page ${i + 1} of ${this.selectedImages.length}...`);
        const opt = await optimizeImageForOcr(item.file);
        preparedImages.push({
          name: getOptimizedFileName(item.file.name),
          mimeType: opt.mimeType,
          arrayBuffer: opt.arrayBuffer,
          base64Data: opt.base64Data
        });
      }
      let noteFolderPath = "";
      if (this.targetMode === "append" && this.activeFile) {
        noteFolderPath = this.activeFile.parent?.path || "";
      } else {
        const parentFolder = this.app.fileManager.getNewFileParent(this.activeFile ? this.activeFile.path : "");
        noteFolderPath = parentFolder && parentFolder.path !== "/" ? parentFolder.path : "";
      }
      this.updateStatus("Saving page images to scans subfolder...");
      const savedTFiles = await saveImagesToVault(
        this.app,
        preparedImages,
        this.plugin.settings,
        noteFolderPath
      );
      const effectiveModel = getEffectiveModel(this.plugin.settings);
      this.updateStatus(`Transcribing ${preparedImages.length} page(s) with ${effectiveModel}...`);
      const transcription = await transcribeImagesWithGemini({
        apiKey: this.plugin.settings.apiKey,
        model: effectiveModel,
        images: preparedImages.map((p) => ({
          mimeType: p.mimeType,
          base64Data: p.base64Data
        })),
        userCustomPrompt: this.plugin.settings.customPrompt,
        noteSpecificInstruction: this.customInstructions,
        enablePageBreaks: this.enablePageBreaks
      });
      this.updateStatus("Building note and embedding scans...");
      const targetPath = this.targetMode === "append" && this.activeFile ? this.activeFile.path : noteFolderPath ? `${noteFolderPath}/note.md` : "note.md";
      const formattedContent = formatNoteWithCallouts(
        this.app,
        transcription,
        savedTFiles,
        { ...this.plugin.settings, enablePageBreaks: this.enablePageBreaks },
        targetPath
      );
      const result = await writeNoteContent(
        this.app,
        formattedContent,
        this.targetMode,
        this.activeFile,
        this.newNoteTitle,
        noteFolderPath
      );
      if (result.isNewFile) {
        const leaf = this.app.workspace.getLeaf(false);
        await leaf.openFile(result.targetFile);
        new import_obsidian4.Notice(`Created new note: "${result.targetFile.basename}"`);
      } else {
        new import_obsidian4.Notice(`Appended digitized pages to "${result.targetFile.basename}"`);
      }
      this.selectedImages.forEach((img) => URL.revokeObjectURL(img.previewUrl));
      this.close();
    } catch (error) {
      console.error("Transcription error:", error);
      this.setLoading(false);
      const errMsg = error.message || "An unexpected error occurred during transcription.";
      if (this.statusMessageEl) {
        this.statusMessageEl.empty();
        this.statusMessageEl.createEl("span", {
          cls: "digitizer-error-text",
          text: `Error: ${errMsg}`
        });
      }
      new import_obsidian4.Notice(`Transcription failed: ${errMsg}`);
    }
  }
  updateStatus(msg) {
    if (this.statusMessageEl) {
      this.statusMessageEl.empty();
      this.statusMessageEl.createDiv({ cls: "digitizer-loading-spinner" });
      this.statusMessageEl.createSpan({ text: msg, cls: "digitizer-loading-text" });
    }
  }
  setLoading(loading, msg = "") {
    this.isProcessing = loading;
    if (this.submitButtonEl) {
      this.submitButtonEl.disabled = loading;
      this.submitButtonEl.setText(loading ? "Processing..." : "Digitize & Transcribe");
    }
    if (loading) {
      this.updateStatus(msg);
    }
  }
  onClose() {
    this.selectedImages.forEach((img) => URL.revokeObjectURL(img.previewUrl));
    this.selectedImages = [];
    const { contentEl } = this;
    contentEl.empty();
  }
};
function getOptimizedFileName(originalName) {
  const lastDot = originalName.lastIndexOf(".");
  const base = lastDot !== -1 ? originalName.substring(0, lastDot) : originalName;
  return `${base}.jpg`;
}
async function optimizeImageForOcr(file, maxDimension = 1920, quality = 0.85) {
  return new Promise((resolve) => {
    const img = new Image();
    const objectUrl = URL.createObjectURL(file);
    img.onload = () => {
      URL.revokeObjectURL(objectUrl);
      let { width, height } = img;
      if (width > maxDimension || height > maxDimension) {
        if (width > height) {
          height = Math.round(height * maxDimension / width);
          width = maxDimension;
        } else {
          width = Math.round(width * maxDimension / height);
          height = maxDimension;
        }
      }
      const canvas = document.createElement("canvas");
      canvas.width = width;
      canvas.height = height;
      const ctx = canvas.getContext("2d");
      if (!ctx) {
        fallbackRead(file).then(resolve);
        return;
      }
      ctx.drawImage(img, 0, 0, width, height);
      canvas.toBlob(
        async (blob) => {
          if (!blob) {
            fallbackRead(file).then(resolve);
            return;
          }
          const arrayBuffer = await blob.arrayBuffer();
          resolve({
            arrayBuffer,
            base64Data: (0, import_obsidian4.arrayBufferToBase64)(arrayBuffer),
            mimeType: "image/jpeg"
          });
        },
        "image/jpeg",
        quality
      );
    };
    img.onerror = () => {
      URL.revokeObjectURL(objectUrl);
      fallbackRead(file).then(resolve);
    };
    img.src = objectUrl;
  });
}
async function fallbackRead(file) {
  const arrayBuffer = await file.arrayBuffer();
  return {
    arrayBuffer,
    base64Data: (0, import_obsidian4.arrayBufferToBase64)(arrayBuffer),
    mimeType: file.type || "image/jpeg"
  };
}

// src/main.ts
var NotebookDigitizerPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("camera", "Digitize Handwritten Notes", () => {
      new DigitizeModal(this.app, this).open();
    });
    this.addCommand({
      id: "digitize-handwritten-notes",
      name: "Digitize Handwritten Notes",
      callback: () => {
        new DigitizeModal(this.app, this).open();
      }
    });
    this.addCommand({
      id: "append-handwritten-notes-to-active",
      name: "Append Handwritten Notes to Active File",
      checkCallback: (checking) => {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile && activeFile.extension === "md") {
          if (!checking) {
            new DigitizeModal(this.app, this, "append").open();
          }
          return true;
        }
        return false;
      }
    });
    this.addSettingTab(new NotebookDigitizerSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
